#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

file="/etc/passwd"

# Use IFS to read the file by colon
while IFS=':' read -r username x userid x homedir x; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < "$file"
