#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for file in *; do
    # Check if the file is not hidden
    if [ "${file:0:1}" != "." ]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        # Display the modified name
        echo "$name_after_dash"
    fi
done
